model:
  name: ""      #Can be a hugging face hub model or local
  task: ""      #Model task

input:
  mode: "csv"  # csv or db
  csv:
    path: "/path/to/your/csv"
    column: "column_name"
  db:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "yourpassword"
    database: ""
    schema: ""
    table: ""
    column: ""

benchmark:                                    
  batch_size: 5
  runs: 1
  warmup_runs: 1
  save_output: true
  output_path: "/path/to/your/output/benchmark_output.csv"

system:
  device: "auto"  # auto/cpu/cuda
  num_threads: 4
