model:
  name: ""      #Can be a hugging face hub model or local
  task: ""      #Model task

input:
  mode: "csv"  # csv or db
  csv:
    path: "/Users/cvarun/Documents/NOTES/1000_notes_for_varun_deid_testing_14_feb_2025 copy.csv"
    column: "note_text"

benchmark:                                    
  batch_size: 32  # Increased for better CPU utilization
  runs: 2
  warmup_runs: 1
  save_output: true
  output_path: ""

system:
  device: "cpu"  #or cuda
  num_threads: 8  # Increased thread count for better CPU utilization
