model:
  name: "dbmdz/bert-large-cased-finetuned-conll03-english"
  task: "ner"

input:
  mode: "csv"  # csv or db
  csv:
    path: "/Users/cvarun/Downloads/100_notes_for_varun_deid_testing_14_feb_2025.csv"
    column: "note_text"
  db:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "yourpassword"
    database: ""
    schema: ""
    table: ""
    column: ""

benchmark:
  batch_size: 5
  runs: 1
  warmup_runs: 1
  save_output: true
  output_path: "/Users/cvarun/Documents/BenchResults/benchmark_output.csv"

system:
  device: "auto"  # auto/cpu/cuda
  num_threads: 4
